### PR TITLE
Studio-12604, SE-11503: Studio memory issues

### PR DESCRIPTION
**Pull request by mauriarroqui**
Cache Strategie in SchemaGenerator: Change Map by Guava Cache.

https://github.com/google/guava/wiki/CachesExplained Guava cache documentation where cache options are explained. In this document is mentioned the preferable use of cache fixed size over soft reference, because of the performance impact of the last option.
Additionally, equals method was added.

### CODE REVIEW

**Comment by jpbelang** [comment]
I'll review tomorrow morning.

**Comment by martincousido** [comment]
Hi @jpbelang Have you had a chance to take a look at the fix?

**Comment by jpbelang** [comment]
Sorry, got caught up in other stuff.  The only thing is the property name: 

`org.mule.tooling.jsonCache`

Could we go for something more neutral as it were ?

**Comment by mauriarroqui** [comment]
Hi @jpbelang, I made the change.

**Comment by jstoiko** [comment]
@mauriarroqui: same comment here regarding your PR title, let's make them a little more descritptive since this is a public repository. Thanks anyway (a lot) for your PR!

**Comment by mauriarroqui** [comment]
ok @jstoiko, sorry for that!

**Pull request merged**
